prepare for v1 (#6)
* prepare for v1

* add usage docs

* pretty

* current url use channel and test version install

* bunble

* formatting test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,9 +53,54 @@ jobs:
         id: checkout
         uses: actions/checkout@v4
 
-      - name: Test Local Action
+      - name: Install up
         id: test-action
         uses: ./
         with:
-          token: test-token
-          skip_login: true
+          api-token: ${{ secrets.UP_API_TOKEN }}
+          organization: github-actions-test
+
+      - name: Verify Installation
+        run: up version
+
+  test-action-skip-login:
+    name: GitHub Actions Test skip-login
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v4
+
+      - name: Install up
+        id: test-action
+        uses: ./
+        with:
+          skip-login: true
+
+      - name: Verify Installation
+        run: up version
+
+  test-action-skip-login-custom-version:
+    name: GitHub Actions Test custom version
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v4
+
+      - name: Install up
+        id: test-action
+        uses: ./
+        with:
+          version: v0.32.0
+          skip-login: true
+
+      - name: Verify Installation
+        run: |
+          INSTALLED_VERSION=$(up version --client | yq .Client.Version)
+          if [[ "$INSTALLED_VERSION" != "v0.32.0" ]]; then
+            echo "Error: Expected version v0.32.0 but got $INSTALLED_VERSION"
+            exit 1
+          fi
